version: '3.8'

services:
  auth_db:
    image: postgres:latest
    container_name: auth_db
    environment:
      POSTGRES_DB: auth_db
      POSTGRES_USER: ${DB_USERNAME_AUTH}
      POSTGRES_PASSWORD: ${DB_PASSWORD_AUTH}
    ports:
      - "5432:5432"
    volumes:
      - auth_db_data:/var/lib/postgresql/data
    networks:
      - backend

  account_db:
    image: postgres:latest
    container_name: account_db
    environment:
      POSTGRES_DB: account_db
      POSTGRES_USER: ${DB_USERNAME_ACCOUNT}
      POSTGRES_PASSWORD: ${DB_PASSWORD_ACCOUNT}
    ports:
      - "5433:5432"
    volumes:
      - account_db_data:/var/lib/postgresql/data
    networks:
      - backend

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_ADMIN_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_ADMIN_POSTGRES}
    ports:
      - "5050:80"
    networks:
      - backend
    depends_on:
      - auth_db
      - account_db

  redis:
    image: redis:latest
    container_name: redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - backend

  rabbitmq:
    image: rabbitmq:management
    container_name: rabbitmq
    environment:
      RABBITMQ_DEFAULT_USER: ${RABBITMQ_USER}
      RABBITMQ_DEFAULT_PASS: ${RABBITMQ_PASS}
    ports:
      - "5672:5672"
      - "15672:15672"
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
    networks:
      - backend

volumes:
  redis_data:
  auth_db_data:
  rabbitmq_data:
  account_db_data:

networks:
  backend:

