server:
  port: 8081


spring:
  application:
    name: AUTH-SERVICE

  datasource:
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/auth_db

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect


application:
  security:
    jwt:
      access-token:
        secret-key: 404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970
        expiration: 86400000 # 1 day
      refresh-token:
        secret-key: 607E436245411A124E1444384292764F098F7683044B4B6250645367566B9870
        expiration: 604800000 # 7 days